"""add finance_records table

Revision ID: e03d415f48e4
Revises: a82839532de6
Create Date: 2026-07-15 18:13:13.136970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e03d415f48e4'
down_revision: Union[str, Sequence[str], None] = 'a82839532de6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finance_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('items_sum', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('delivery_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_paid', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('intermediary_commission', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('after_commission', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_status', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('finance_records')
    # ### end Alembic commands ###
